[project]
name = "bioasq-rag"
version = "0.1.0"
requires-python = ">=3.11"
description = "RAG system for BioASQ"
dependencies = [
]

[tool.uv.workspace]
members = ["data_acquisition", "data_processing", "indexing_pipeline", "search", "rag-traditional", "evaluations"]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]


